import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  // Dancing_Script,
  Fira_Code,
} from "next/font/google";
import "./globals.css";
import FallingHearts from "./components/falling-hearts";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// const dancingScript = Dancing_Script({
//   variable: "--dancing-script",
//   subsets: ["latin"],
//   weight: ["400", "700"],
// });

const firaCode = Fira_Code({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${firaCode.className} antialiased bg-pink-100`}
      >
        <FallingHearts />
        {children}
      </body>
    </html>
  );
}
